services:
  auth-service:
    build: ./auth-service
    ports:
      - "8081:8080"
    networks:
      - todo-net
    depends_on:
      - task-service
      - db
    environment:
      - DB_URL=jdbc:postgresql://db:5432/todo
      - DB_USERNAME=postgres
      - DB_PASSWORD=password
      - SECRET=MzI3NzQ0NzQ4NjcyNDk3MzI5Nzk3NzY2OTQ2MzIzNjY4Nzg5Njk5ODc0NzY2Nzc4NTYzNzQ3Njc5NjY0OTY5Mzc2ODMzNjk5NTg1NzUyOTY0Mzk2OTU2MzY1MzQ5NDY5Nzg1NTM3NzQ2ODk5MjQzNTg2NDg4ODM0NTM5OTkxNzY2MTY4NjE0MjU3Nzc0NzY1MzA1NjE0NzY0NTg1Mzc5MjM5NzM0NTY3NTc0OTc2NjE4NDYyMjI1NTk0OTU4NzQ4MTM5MTg5NjcxNzk2MjE3NzQ5NzUzNzA2MTMxNjk2OTIwNTI5OTI5MzQ1MjY2MDc2NjYxMjQwNjY2NzQ5Njk2NTUwNTMxMTg5OTc4NDc0NDQ3NjkzNjcyNTIwNTg3MjcxMzA5NTg4MzQwNjYzNjM3Nzg2NjkxNzMwMjYxNTA4MjYxOTkwNDg0ODk2MTI5MjQ2MTg3MTMwMjcxMzQwMDQy
      - JWT_TIME=900000
      - RT_TIME=259200000

  task-service:
    build: ./task-service
    ports:
      - "8082:8080"
    networks:
      - todo-net
    depends_on:
      - notification-service
      - db
    environment:
      - DB_URL=jdbc:postgresql://db:5432/todo
      - DB_USERNAME=postgres
      - DB_PASSWORD=password

  notification-service:
    build: ./notification-service
    ports:
      - "8083:8080"
    networks:
      - todo-net
    depends_on:
      - db
    environment:
      - DB_URL=jdbc:postgresql://db:5432/todo
      - DB_USERNAME=postgres
      - DB_PASSWORD=password

  db:
    image: postgres:latest
    container_name: todo-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: todo
    volumes:
      - todo-db-data:/var/lib/postgresql/data
    networks:
      - todo-net
    ports:
      - "5432:5432"

  frontend:
    build: ./todo-frontend
    ports:
      - "3000:3000"
    networks:
      - todo-net
    depends_on:
      - auth-service
      - task-service
      - notification-service

networks:
  todo-net:
    driver: bridge

volumes:
  todo-db-data:
