CREATE TABLE spring_session
(
    PRIMARY_KEY    VARCHAR(36) NOT NULL,
    SESSION_ID     VARCHAR(36) NOT NULL,
    EXPIRY_TIME    BIGINT      NOT NULL,
    PRINCIPAL_NAME VARCHAR(100),
    CONSTRAINT PK_spring_session PRIMARY KEY (SESSION_ID)
);
